import type { Metadata } from "next"
import Link from "next/link"
import { Header } from "@/components/header"
import { Footer } from "@/components/footer"
import { SUPPORT_EMAIL, SUPPORT_MAILTO } from "@/lib/support"

export const metadata: Metadata = {
  title: "Acceptable Use Policy - cartoonphoto",
  description: "Acceptable Use Policy for cartoonphoto.",
}

export default function AcceptableUsePage() {
  return (
    <main className="min-h-screen">
      <Header />

      <div className="container mx-auto max-w-3xl px-4 pt-28 pb-16">
        <h1 className="text-3xl font-bold tracking-tight">Acceptable Use Policy</h1>
        <p className="mt-2 text-sm text-muted-foreground">Last updated: February 28, 2026</p>

        <section className="mt-10 space-y-6 text-sm leading-6 text-foreground">
          <p>
            This Acceptable Use Policy (&quot;AUP&quot;) describes prohibited uses of the cartoonphoto Service. It applies to all
            users and all content submitted to or generated by the Service.
          </p>

          <div className="space-y-2">
            <h2 className="text-base font-semibold">You must not</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li>
                Create, request, upload, or distribute{" "}
                <span className="font-medium">sexual content (NSFW)</span>, including nudity or explicit sexual content.
              </li>
              <li>
                Create, request, upload, or distribute{" "}
                <span className="font-medium">sexual content involving minors</span> or any content that sexualizes
                minors (strictly prohibited).
              </li>
              <li>
                Create, request, upload, or distribute{" "}
                <span className="font-medium">non-consensual intimate imagery</span> (real or synthetic), including
                &quot;revenge porn&quot; or any depiction of a person in a sexual context without clear consent.
              </li>
              <li>
                Create, request, upload, or distribute{" "}
                <span className="font-medium">impersonation, deepfakes, face swaps, or other deceptive content</span>{" "}
                involving real people without their permission (including public figures).
              </li>
              <li>Harass, threaten, or target individuals or protected groups.</li>
              <li>Use the Service for illegal activity, or to create content that violates applicable law.</li>
              <li>Infringe intellectual property rights or privacy/publicity rights.</li>
              <li>
                Attempt to bypass safety filters, rate limits, or security controls, or to reverse engineer the Service.
              </li>
              <li>Upload malware or otherwise attempt to compromise the Service.</li>
            </ul>
          </div>

          <div className="space-y-2">
            <h2 className="text-base font-semibold">Enforcement</h2>
            <p>
              We may remove content, suspend access, terminate accounts, and/or report activity to appropriate parties
              if we believe there is a violation of this AUP or our{" "}
              <Link className="underline" href="/terms">
                Terms of Service
              </Link>
              .
            </p>
          </div>

          <div className="space-y-2">
            <h2 className="text-base font-semibold">Report concerns</h2>
            <p>
              If you believe content violates this policy, contact us at{" "}
              <a className="underline" href={SUPPORT_MAILTO}>
                {SUPPORT_EMAIL}
              </a>
              .
            </p>
          </div>
        </section>
      </div>

      <Footer />
    </main>
  )
}
